name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          # Extract repo name and set the base URL to /repo-name/
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV

          # Update Astro config base dynamically
          npx astro build --base "/${REPO_NAME}/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages # Adjust if you have a different branch for GitHub Pages
